<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calender_Next</name>
   <tag></tag>
   <elementGuidId>03c75e18-35a2-41a4-970a-6bef36ce3d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/a-date-picker[1]/div[1]/div[1]/div[3]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
