<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_Select</name>
   <tag></tag>
   <elementGuidId>099c7b10-7d28-4d69-8cd4-ec285927f58d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/a-date-picker[1]/div[1]/div[3]/div[8]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
